# Generated by Django 6.0.4 on 2026-09-01 21:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('condition', models.CharField(choices=[('pairwise', 'Design 1 · Pairwise choice'), ('ranking', 'Design 2 · Rank a set of 10')], max_length=16)),
                ('consented', models.BooleanField(default=False)),
                ('age_group', models.CharField(blank=True, max_length=32)),
                ('prior_ml_exp', models.CharField(blank=True, max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PairwiseResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_index', models.IntegerField()),
                ('movie_a_id', models.IntegerField()),
                ('movie_b_id', models.IntegerField()),
                ('chosen_movie_id', models.IntegerField()),
                ('response_ms', models.IntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairwise_responses', to='project4.participant')),
            ],
            options={
                'ordering': ['participant', 'trial_index'],
                'indexes': [models.Index(fields=['participant', 'trial_index'], name='project4_pa_partici_b9ae7d_idx')],
            },
        ),
        migrations.CreateModel(
            name='RankingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_index', models.IntegerField()),
                ('shown_ids_json', models.JSONField()),
                ('ranked_ids_json', models.JSONField()),
                ('response_ms', models.IntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_responses', to='project4.participant')),
            ],
            options={
                'ordering': ['participant', 'trial_index'],
                'indexes': [models.Index(fields=['participant', 'trial_index'], name='project4_ra_partici_fbb6f0_idx')],
            },
        ),
    ]
