# Generated by Django 6.0.4 on 2026-09-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='stored basename inside MEDIA_ROOT', max_length=200)),
                ('original_name', models.CharField(max_length=200)),
                ('n_samples', models.IntegerField()),
                ('n_features', models.IntegerField()),
                ('target_col', models.CharField(max_length=100)),
                ('problem_type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
